- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: reload_prometheus
  uri:
    url: http://127.0.0.1:9090/-/reload
    method: POST
    status_code: 200
